name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy_rules_and_app:
    name: Deploy Firestore Rules & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js Application
        run: npm run build

      - name: Deploy Firestore Rules to Firebase
        run: npx firebase-tools deploy --only firestore:rules --token "${{ secrets.FIREBASE_TOKEN }}" --project pulse-app-93
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
